### ISSUE TITLE
Add readme and notebooks for NCRA regions

### ISSUE THREAD

**Issue by xenct** [aus-ref-clim-data-nci/shapefiles#4]
I have added ncra_regions  and NCRA_regions_coastal_waters_GDA94 shape files to /g/data/ia39/aus-ref-clim-data-nci/shapefiles/data/.
These shapefiles do not have the documentation that the existing files do.
I will add to the documentation to ensure consistency of information for users.
I have forked this repo and I intend to make a pull request once I have addressed the above updates.
-Gen

**Comment by DamienIrving** [comment]
Fantastic! Thanks, @xenct.

Let me know if you need any assistance - I'm happy to be tagged to review your pull request.

**Comment by xenct** [comment]
Hi @DamienIrving, 
I have created a pull request to update this repo. Please have a look,
Gen
